# Generated by Django 5.1.4 on 2025-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='platos',
            field=models.ManyToManyField(through='menu.MenuPlato', to='menu.plato'),
        ),
    ]
