# Generated by Django 5.1.4 on 2025-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
    ]
