# Generated by Django 5.1.4 on 2025-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_plato_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='moneda',
            field=models.CharField(default='COP', max_length=10),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=15),
        ),
    ]
