# Generated by Django 5.1.4 on 2025-02-11 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
        ('menu', '0004_alter_plato_moneda_alter_plato_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=20),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(blank=True, null=True)),
                ('hora_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='establecimientos.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pedido')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
            ],
            options={
                'unique_together': {('pedido', 'plato')},
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='platos',
            field=models.ManyToManyField(through='menu.PedidoPlato', to='menu.plato'),
        ),
    ]
