# Generated by Django 5.1.4 on 2025-02-13 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_plato_precio_pedido_pedidoplato_pedido_platos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidoplato',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoplato',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
