# Generated by Django 5.1.4 on 2025-02-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
        ('menu', '0006_alter_pedidoplato_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.establecimiento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
