# Generated by Django 5.1.4 on 2025-02-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_pedido_establecimiento_pedido_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='establecimiento',
        ),
        migrations.AlterField(
            model_name='pedidoplato',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
