# Generated by Django 5.1.4 on 2025-02-13 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_pedido_establecimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='moneda',
        ),
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
