# Generated by Django 5.1.4 on 2025-02-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_menu_establecimiento_remove_menu_platos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu.establecimiento'),
            preserve_default=False,
        ),
    ]
